In [1]:
import numpy as np
import pandas as pd
import keras

#importing Keras, Library for deep learning 
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D

from sklearn.model_selection import train_test_split

In [2]:
#LOAD DATA
from sklearn.datasets import load_digits
digits = load_digits()
#DATAFRAMING
df_y = pd.DataFrame(data=digits.target).iloc[:,0]
df_x = pd.DataFrame(data=digits.data, columns=digits.feature_names)

In [3]:
df_x.head(5)

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [4]:
df_y = np.array(df_y)
print(df_y)

[0 1 2 ... 8 9 8]


In [5]:
#reshaping data to 8x8 array
#df_x.iloc[0].values.reshape(8,8).astype('uint8')

In [6]:
new_df_x = digits.data.reshape(len(digits.data),8,8,1).astype('uint8')

new_df_x = np.array(new_df_x)

print(new_df_x)

[[[[ 0]
   [ 0]
   [ 5]
   ...
   [ 1]
   [ 0]
   [ 0]]

  [[ 0]
   [ 0]
   [13]
   ...
   [15]
   [ 5]
   [ 0]]

  [[ 0]
   [ 3]
   [15]
   ...
   [11]
   [ 8]
   [ 0]]

  ...

  [[ 0]
   [ 4]
   [11]
   ...
   [12]
   [ 7]
   [ 0]]

  [[ 0]
   [ 2]
   [14]
   ...
   [12]
   [ 0]
   [ 0]]

  [[ 0]
   [ 0]
   [ 6]
   ...
   [ 0]
   [ 0]
   [ 0]]]


 [[[ 0]
   [ 0]
   [ 0]
   ...
   [ 5]
   [ 0]
   [ 0]]

  [[ 0]
   [ 0]
   [ 0]
   ...
   [ 9]
   [ 0]
   [ 0]]

  [[ 0]
   [ 0]
   [ 3]
   ...
   [ 6]
   [ 0]
   [ 0]]

  ...

  [[ 0]
   [ 0]
   [ 1]
   ...
   [ 6]
   [ 0]
   [ 0]]

  [[ 0]
   [ 0]
   [ 1]
   ...
   [ 6]
   [ 0]
   [ 0]]

  [[ 0]
   [ 0]
   [ 0]
   ...
   [10]
   [ 0]
   [ 0]]]


 [[[ 0]
   [ 0]
   [ 0]
   ...
   [12]
   [ 0]
   [ 0]]

  [[ 0]
   [ 0]
   [ 3]
   ...
   [14]
   [ 0]
   [ 0]]

  [[ 0]
   [ 0]
   [ 8]
   ...
   [16]
   [ 0]
   [ 0]]

  ...

  [[ 0]
   [ 9]
   [16]
   ...
   [ 0]
   [ 0]
   [ 0]]

  [[ 0]
   [ 3]
   [13]
   ...
   [11]
   [ 5]
   [ 0]]

  [[ 0

In [7]:
#PREPROCESSING DATA
#df_x = np.array(df_x)
#print(df_x)
#df_x.shape

In [8]:
new_df_y = keras.utils.to_categorical(df_y,num_classes=10)
new_df_y = np.array(new_df_y)

In [9]:
print(df_y[57])
print(new_df_y[57])

2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
x_train, x_test, y_train, y_test = train_test_split(new_df_x, new_df_y, test_size=0.2, random_state=4)

In [11]:
#CNN MODEL
model = Sequential()
model.add(Convolution2D(16,3,data_format='channels_last',activation='relu',input_shape=(8,8,1)))
model.add(MaxPooling2D(pool_size=(1,1)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics = ['accuracy'])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 6, 6, 16)          160       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 6, 6, 16)          0         
_________________________________________________________________
flatten (Flatten)            (None, 576)               0         
_________________________________________________________________
dense (Dense)                (None, 100)               57700     
_________________________________________________________________
dropout (Dropout)            (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1010      
_________________________________________________________________
activation (Activation)      (None, 10)                0

In [13]:
model.fit(x_train,y_train,validation_data=(x_test,y_test))

45/45 [==============================] - 0s 7ms/step - loss: 9.5688 - accuracy: 0.0932 - val_loss: 6.4873 - val_accuracy: 0.1333
