In [12]:
# keras imports for the dataset and building our neural network
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten
from keras.utils import np_utils

# to calculate accuracy
from sklearn.metrics import accuracy_score

In [13]:
# loading the dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [14]:
# building the input vector from the 28x28 pixels
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# normalizing the data to help with the training
X_train /= 255
X_test /= 255


In [17]:
print(X_test.shape)

(10000, 28, 28, 1)


In [18]:
# one-hot encoding using keras' numpy-related utilities
n_classes = 10
print("Shape before one-hot encoding: ", y_train.shape)
Y_train = np_utils.to_categorical(y_train, n_classes)
Y_test = np_utils.to_categorical(y_test, n_classes)
print("Shape after one-hot encoding: ", Y_train.shape)

Shape before one-hot encoding:  (60000,)
Shape after one-hot encoding:  (60000, 10)


In [19]:
print(Y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [20]:
# building a linear stack of layers with the sequential model
model = Sequential()
# convolutional layer
model.add(Conv2D(25, kernel_size=(3,3), strides=(1,1), padding='valid', activation='relu', input_shape=(28,28,1)))
model.add(MaxPool2D(pool_size=(1,1)))
# flatten output of conv
model.add(Flatten())
# hidden layer
model.add(Dense(100, activation='relu'))
# output layer
model.add(Dense(10, activation='softmax'))

In [21]:
# compiling the sequential model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

# training the model for 10 epochs
model.fit(X_train, Y_train, batch_size=128, epochs=10, validation_data=(X_test, Y_test))

Epoch 1/10
469/469 [==============================] - 17s 37ms/step - loss: 0.1978 - accuracy: 0.9418 - val_loss: 0.0860 - val_accuracy: 0.9725
Epoch 2/10
469/469 [==============================] - 18s 38ms/step - loss: 0.0643 - accuracy: 0.9808 - val_loss: 0.0606 - val_accuracy: 0.9789
Epoch 3/10
469/469 [==============================] - 19s 41ms/step - loss: 0.0389 - accuracy: 0.9882 - val_loss: 0.0528 - val_accuracy: 0.9827
Epoch 4/10
469/469 [==============================] - 20s 42ms/step - loss: 0.0244 - accuracy: 0.9928 - val_loss: 0.0520 - val_accuracy: 0.9840
Epoch 5/10
469/469 [==============================] - 19s 40ms/step - loss: 0.0161 - accuracy: 0.9951 - val_loss: 0.0520 - val_accuracy: 0.9840
Epoch 6/10
469/469 [==============================] - 22s 46ms/step - loss: 0.0111 - accuracy: 0.9968 - val_loss: 0.0554 - val_accuracy: 0.9823
Epoch 7/10
469/469 [==============================] - 20s 43ms/step - loss: 0.0074 - accuracy: 0.9980 - val_loss: 0.0541 - val_accuracy: